apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-params
spec:
  params:
  - name: target
    type: string
    description: name to greet
    default: icloud2native
  steps:
  - name: say-hello
    image: alpine:3.15
    command:
    - /bin/sh
    args: ['-c','echo $(params.target)']
