apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: script
spec:
  steps:
  - name: step-with-script
    image: alpine:3.15
    script: |
      #/bin/sh
      echo "step witk script start ..."
      echo "Installing necessary tools ..."
      apk add curl
      curl -s www.baidu.com && echo "Success" || echo "Failed"
      echo "All done"
