apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-to-package
spec:
  workspaces:
  - name: source
    description: The code repo in the workspaces
  steps:
  - name: build
    image: maven:3.8-openjdk-11-slim
    workingDir: $(workspaces.source.path)/source
    volumeMounts:
    - name: m2
      mountPath: /root/.m2
    script: mvn clean install
  # 定义volume提供maven cache，但是前提得创建出来maven-cache的pvc
  volumes:
  - name: m2
    persistentVolumeClaim:
      claimName: maven-cache

